app/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api

from flask_migrate import Migrate
from models import db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder



app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
db.init_app(app)
login_manager.init_app(app)
login_manager.login_view = "auth.signin"
ma.init_app(app)
migrate = Migrate(app, db)

app/api/routes.py
from flask import Blueprint, render_template, request, jsonify
from helpers import token_required
from models import db, Expense, expense_schema

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/checkexpenses', methods=['GET', 'POST'])
@token_required
def get_expenses(current_user_token):
    expense = Expense.query.filter_by(user_token=current_user_token.token).first()

    if expense:
        response = {
            "message": "Expense data saved successfully.",
            "expense_list": expense.expense_list,
            "needs": expense.needs,
            "savings": expense.savings,
            "wants": expense.wants,
            "income": expense.income,
            "total_expenses": expense.total_expenses,
            "surplus_deficit": expense.surplus_deficit
        }
    else:
        response = "User and/or data not found"

    return jsonify(response), 200


@api.route('/createexpenses', methods=['GET', 'POST'])
@token_required
def create_expenses(current_user_token):
    # Default expenses if no data in db for user
    expense_list = {
        'housing': 0.00,
        'transportation': 0.00,
        'groceries': 0.00,
        'utilities': 0.00,
        'healthcare': 0.00,
        'debt payments': 0.00,
        'emergency fund': 0.00,
        'retirement': 0.00,
        'vacation': 0.00,
        'entertainment': 0.00,
        'dining out': 0.00,
        'hobbies': 0.00
    }
    needs = [
        'housing',
        'transportation',
        'groceries',
        'utilities',
        'healthcare',
        'debt payments'
    ]
    savings = [
        'emergency fund',
        'retirement',
        'vacation'
    ]
    wants = [
        'entertainment',
        'dining out',
        'hobbies'
    ]
    income = 0.00
    total_expenses = 0.00
    surplus_deficit = 0.00
    user_token = current_user_token.token

    expense = Expense(
        expense_list = expense_list,
        needs = needs,
        savings = savings,
        wants = wants,
        income = income,
        total_expenses = total_expenses,
        surplus_deficit = surplus_deficit,
        user_token = user_token
    )
    
    db.session.add(expense)
    db.session.commit()

    response = "Data not created, please try again"


    return jsonify(response), 201


@api.route('/updateexpenses', methods=['GET', 'PUT'])
@token_required
def update_expenses(current_user_token):
    if not current_user_token:
        return jsonify({"message": "Token is missing or invalid."}), 401

    user_token = current_user_token.token

    expense = Expense.query.filter_by(user_token=user_token).first()

    if not expense:
        return jsonify({"message": "Expense list not found."}), 404
    
    expense_name = request.json.get('expense_name')
    expense_value = request.json.get('expense_value')

    if expense_name and expense_value:
        # Update the expense_list with the custom expense
        expense.expense_list[expense_name] = expense_value

    # Determine what category possible user added / custom expense needs to go to
    category = request.json.get('category')
    if category == 'needs':
        expense.needs.append(expense_name)
    elif category == 'savings':
        expense.savings.append(expense_name)
    elif category == 'wants':
        expense.wants.append(expense_name)    

    expense.expense_list = request.json['expense_list']
    expense.needs = request.json['needs']
    expense.savings = request.json['savings']
    expense.wants = request.json['wants']
    expense.income = request.json['income']
    expense.total_expenses = request.json['total_expenses']
    expense.surplus_deficit = request.json['surplus_deficit']
    expense.user_token = current_user_token.token

    db.session.commit()
    response = expense_schema.dump(expense)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm, UserSignupForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignupForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            first_name = form.first_name.data.title()
            last_name = form.last_name.data.title()


            user = User(email, first_name, last_name, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {first_name}', 'User-created')
            return redirect(url_for('site.index'))
        
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your initiation. Congrats and welcome!', 'auth-success')
                return redirect(url_for('site.profile'))
            
            else:
                flash('You have failed in your attempt to access this content.', 'auth-failed')

    except:
        raise Exception('Invalid form data: please check your form')
    return render_template('sign_in.html', form = form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.index'))

app/site/routes.py
from flask import Blueprint, render_template
import requests
from flask_login import current_user, login_required

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def index():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

@site.route('/budget')
@login_required
def budget():
        return render_template('budget.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/styles.css">
<title>Budget</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark text-success navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="{{ url_for('site.index') }}" class="navbar-brand text-success" id="budget_link">Budget</a>
            <button 
                class="navbar-toggler color-success" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto text-center">
                    <li class="nav-item">
                        <a href="{{ url_for('site.index') }}" class="nav-link text-success ms-lg-4">Home</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('site.budget') }}" class="nav-link text-success ms-lg-4">Budget</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link text-success ms-lg-4">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link text-success ms-lg-4">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link text-success ms-lg-4">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link text-success ms-lg-4">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/sign_in_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            <h6>Email</h6>
            {{ form.email(class = 'form-control', placeholder = 'Enter email here...') }}
        </fieldset>
    </div>

    <div class="form-group">
        <fieldset id="pass-field">
            <h6>Password</h6>
            {{ form.password(class = 'form-control', placeholder = 'Enter password here...') }}
        </fieldset>
    </div>
    <div class="text-center mt-4">
        {{ form.submit_button(class = "btn btn-success") }}
    </div>

</form>

<!-- Link to Sign Up if they don't have account -->
<p class="mt-3 text-center">Don't have an account? <a href="{{ url_for('auth.signup') }}">Sign Up</a></p>

app/templates/sign_up_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            <h6>Email</h6>
            {{ form.email(class = 'form-control', placeholder = 'Enter email here...') }}
        </fieldset>
    </div>
    <div>
        <fieldset id="pass-field">
            <h6>Password</h6>
            {{ form.password(class = 'form-control', placeholder = 'Enter password here...') }}
        </fieldset>
    </div>
    <div>
        <fieldset id="first-field">
            <h6>First name</h6>
            {{ form.first_name(class = 'form-control', placeholder = 'Enter first name here...') }}
        </fieldset>
    </div>
    <div class="form-group">
        <fieldset id="last-field">
            <h6>Last name</h6>
            {{ form.last_name(class = 'form-control', placeholder = 'Enter last name here...') }}
        </fieldset>
    </div>
    <div class="text-center mt-4">
        {{ form.submit_button(class = "btn btn-success") }}
    </div>

</form>